version: '3.8'
services:
  mysql-primary-1:
    image: mysql:5.7
    command: --max_allowed_packet=256M
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword1
    ports:
      - "3306:3306"
    volumes:
      - ../sql_data:/sql_data
      - mysql-primary-1-data:/var/lib/mysql
    networks:
      - mynetwork
  mysql-primary-2:
    image: mysql:5.7
    command: --max_allowed_packet=256M
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword2
    ports:
      - "3307:3306"
    volumes:
      - ../sql_data:/sql_data
      - mysql-primary-2-data:/var/lib/mysql
    networks:
      - mynetwork
  mysql-backup-1:
    image: mysql:5.7
    command: --max_allowed_packet=256M
    environment:
      MYSQL_ROOT_PASSWORD: backuppassword1
    ports:
      - "3308:3306"
    volumes:
      - ../sql_data:/sql_data
      - mysql-backup-1-data:/var/lib/mysql
    networks:
      - mynetwork
  mysql-backup-2:
    image: mysql:5.7
    command: --max_allowed_packet=256M
    environment:
      MYSQL_ROOT_PASSWORD: backuppassword2
    ports:
      - "3309:3306"
    volumes:
      - ../sql_data:/sql_data
      - mysql-backup-2-data:/var/lib/mysql
    networks:
      - mynetwork
  # Hadoop NameNode (master node)
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    volumes:
      - ../sql_data/articles:/articles
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - hadoop.env
    ports:
      - "9870:9870"
    networks:
      - mynetwork
  # Hadoop DataNode (worker node)
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    volumes:
      - ../sql_data/articles:/articles
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - hadoop.env
    networks:
      - mynetwork
  myapp:
    image: openjdk:17
    volumes:
      - ../datacenter/build/libs:/app
    working_dir: /app
    command: java -jar myapplication.jar
    ports:
      - "8080:8080"
    networks:
      - mynetwork

volumes:
  mysql-primary-1-data:
  mysql-primary-2-data:
  mysql-backup-1-data:
  mysql-backup-2-data:
  hadoop_namenode:
  hadoop_datanode:

networks:
  mynetwork:
    driver: bridge
