global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter-1:9104', 'mysql-exporter-2:9105', 'mysql-exporter-3:9106', 'mysql-exporter-4:9107']
